export type Variety = {
  id: string
  name: string
  year: number
  country: string
  color: 'red' | 'green' | 'yellow' | 'pink' | 'bicolor'
  parents: [string, string] | null
  taste: string
  notes?: string
}

export const varieties: Variety[] = [
  {
    id: 'wagener',
    name: 'Wagener',
    year: 1796,
    country: 'USA',
    color: 'bicolor',
    parents: null,
    taste: 'Säuerlich-würzig, fest',
    notes: 'Historische Sorte, Zufallssämling.',
  },
  {
    id: 'mcintosh',
    name: 'McIntosh',
    year: 1811,
    country: 'Kanada',
    color: 'red',
    parents: null,
    taste: 'Süß, leicht würzig, weich',
    notes: 'Zufallssämling, gefunden von John McIntosh.',
  },
  {
    id: 'cox',
    name: 'Cox Orange Pippin',
    year: 1825,
    country: 'England',
    color: 'bicolor',
    parents: null,
    taste: 'Aromatisch, würzig, süß-säuerlich',
    notes: 'Vermutlich aus Sämling der Ribston Pippin.',
  },
  {
    id: 'jonathan',
    name: 'Jonathan',
    year: 1826,
    country: 'USA',
    color: 'red',
    parents: null,
    taste: 'Süß-säuerlich, knackig',
  },
  {
    id: 'boskoop',
    name: 'Schöner aus Boskoop',
    year: 1856,
    country: 'Niederlande',
    color: 'bicolor',
    parents: null,
    taste: 'Säuerlich, fest, würzig',
    notes: 'Klassischer Back- und Mostapfel.',
  },
  {
    id: 'granny-smith',
    name: 'Granny Smith',
    year: 1868,
    country: 'Australien',
    color: 'green',
    parents: null,
    taste: 'Sauer, knackig, fest',
    notes: 'Zufallssämling von Maria Ann Smith.',
  },
  {
    id: 'red-delicious',
    name: 'Red Delicious',
    year: 1880,
    country: 'USA',
    color: 'red',
    parents: null,
    taste: 'Süß, mild, fest',
  },
  {
    id: 'golden-delicious',
    name: 'Golden Delicious',
    year: 1890,
    country: 'USA',
    color: 'yellow',
    parents: null,
    taste: 'Süß, mild, saftig',
    notes: 'Wichtiger Elternteil vieler moderner Sorten.',
  },
  {
    id: 'ingrid-marie',
    name: 'Ingrid Marie',
    year: 1910,
    country: 'Dänemark',
    color: 'red',
    parents: null,
    taste: 'Aromatisch, süß-säuerlich',
    notes: 'Vermutlich Sämling aus Cox Orange.',
  },
  {
    id: 'kidds-orange',
    name: "Kidd's Orange Red",
    year: 1924,
    country: 'Neuseeland',
    color: 'bicolor',
    parents: ['cox', 'red-delicious'],
    taste: 'Süß-aromatisch, saftig',
  },
  {
    id: 'gala',
    name: 'Gala',
    year: 1934,
    country: 'Neuseeland',
    color: 'bicolor',
    parents: ['kidds-orange', 'golden-delicious'],
    taste: 'Süß, mild, knackig',
  },
  {
    id: 'lady-williams',
    name: 'Lady Williams',
    year: 1935,
    country: 'Australien',
    color: 'red',
    parents: null,
    taste: 'Süß-säuerlich, sehr lange haltbar',
  },
  {
    id: 'idared',
    name: 'Idared',
    year: 1935,
    country: 'USA',
    color: 'red',
    parents: ['jonathan', 'wagener'],
    taste: 'Süß-säuerlich, fest',
  },
  {
    id: 'fuji',
    name: 'Fuji',
    year: 1939,
    country: 'Japan',
    color: 'bicolor',
    parents: ['red-delicious', 'ralls-janet'],
    taste: 'Süß, knackig, sehr saftig',
  },
  {
    id: 'ralls-janet',
    name: 'Ralls Janet',
    year: 1793,
    country: 'USA',
    color: 'bicolor',
    parents: null,
    taste: 'Süß-säuerlich',
    notes: 'Alte amerikanische Sorte, Elternteil von Fuji.',
  },
  {
    id: 'braeburn',
    name: 'Braeburn',
    year: 1952,
    country: 'Neuseeland',
    color: 'bicolor',
    parents: null,
    taste: 'Süß-säuerlich, knackig',
    notes: 'Zufallssämling, vermutlich Lady Hamilton × Granny Smith.',
  },
  {
    id: 'jonagold',
    name: 'Jonagold',
    year: 1953,
    country: 'USA',
    color: 'bicolor',
    parents: ['jonathan', 'golden-delicious'],
    taste: 'Süß-säuerlich, saftig',
  },
  {
    id: 'elstar',
    name: 'Elstar',
    year: 1955,
    country: 'Niederlande',
    color: 'bicolor',
    parents: ['golden-delicious', 'ingrid-marie'],
    taste: 'Süß-säuerlich, aromatisch',
  },
  {
    id: 'rubinette',
    name: 'Rubinette',
    year: 1966,
    country: 'Schweiz',
    color: 'bicolor',
    parents: ['golden-delicious', 'cox'],
    taste: 'Aromatisch, süß-säuerlich',
  },
  {
    id: 'clivia',
    name: 'Clivia',
    year: 1965,
    country: 'Deutschland',
    color: 'red',
    parents: null,
    taste: 'Süß-säuerlich',
    notes: 'Züchtung aus Müncheberg.',
  },
  {
    id: 'pink-lady',
    name: 'Pink Lady (Cripps Pink)',
    year: 1973,
    country: 'Australien',
    color: 'pink',
    parents: ['lady-williams', 'golden-delicious'],
    taste: 'Süß-säuerlich, knackig',
  },
  {
    id: 'topaz',
    name: 'Topaz',
    year: 1984,
    country: 'Tschechien',
    color: 'bicolor',
    parents: ['rubin', 'vanda'],
    taste: 'Säuerlich-aromatisch, schorfresistent',
  },
  {
    id: 'rubin',
    name: 'Rubin',
    year: 1960,
    country: 'Tschechien',
    color: 'red',
    parents: ['golden-delicious', 'lord-lambourne'],
    taste: 'Süß-säuerlich',
  },
  {
    id: 'vanda',
    name: 'Vanda',
    year: 1968,
    country: 'Tschechien',
    color: 'red',
    parents: null,
    taste: 'Säuerlich-fest',
    notes: 'Elternteil von Topaz.',
  },
  {
    id: 'lord-lambourne',
    name: 'Lord Lambourne',
    year: 1907,
    country: 'England',
    color: 'bicolor',
    parents: null,
    taste: 'Süß-aromatisch',
  },
  {
    id: 'pinova',
    name: 'Pinova',
    year: 1986,
    country: 'Deutschland',
    color: 'bicolor',
    parents: ['clivia', 'golden-delicious'],
    taste: 'Süß-aromatisch, saftig',
  },
]

export const varietyById = (id: string): Variety | undefined =>
  varieties.find((v) => v.id === id)

// Crosses where both parents exist in the data set – used for the practice game.
export const crosses = varieties.filter(
  (v) =>
    v.parents !== null &&
    varietyById(v.parents[0]) !== undefined &&
    varietyById(v.parents[1]) !== undefined,
)
